# Generated by Django 4.2.5 on 2023-09-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='coefficient',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Hệ số 1'), (2, 'Hệ số 2'), (3, 'Hệ số 3')], default=1),
        ),
    ]
