# Generated by Django 4.2.5 on 2023-09-16 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0002_alter_contest_coefficient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Câu trả lời', 'verbose_name_plural': 'Câu trả lời'},
        ),
        migrations.AlterModelOptions(
            name='contest',
            options={'verbose_name': 'Bài kiểm tra', 'verbose_name_plural': 'Bài kiểm tra'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Câu hỏi', 'verbose_name_plural': 'Câu hỏi'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(verbose_name='Nội dung câu trả lời'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hình ảnh câu trả lời'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Đây là đáp án đúng'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.question', verbose_name='Câu hỏi'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo cuộc thi'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='coefficient',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Hệ số 1'), (2, 'Hệ số 2'), (3, 'Hệ số 3')], default=1, verbose_name='Hệ số'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(verbose_name='Thời gian kết thúc'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên cuộc thi'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(verbose_name='Thời gian bắt đầu'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(verbose_name='Nội dung câu hỏi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest', verbose_name='Cuộc thi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficult_level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Độ khó'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hình ảnh câu hỏi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_select_multiple',
            field=models.BooleanField(default=False, verbose_name='Cho phép chọn nhiều đáp án'),
        ),
    ]
