# Generated by Django 4.2.5 on 2023-09-20 03:51

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_alter_answer_options_alter_contest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/Users/nals_macbook_177/Desktop/tkp-quiz/src/../.static/contest/answer'), verbose_name='Hình ảnh câu trả lời'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/Users/nals_macbook_177/Desktop/tkp-quiz/src/../.static/contest/question'), verbose_name='Hình ảnh câu hỏi'),
        ),
    ]
