# Generated by Django 4.2.5 on 2023-09-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_classroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tên lớp học'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Năm học'),
        ),
    ]
