# Generated by Django 5.0 on 2023-12-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_alter_classroom_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
