# Generated by Django 4.2.8 on 2024-01-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Chưa có họ và tên', max_length=255, verbose_name='Họ và tên'),
            preserve_default=False,
        ),
    ]
