version: "2.3"
services:
  # TKP Quiz server
  tkp-quiz:
    build:
      context: ../
      dockerfile: docker/dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../src:/src
      - ../.env:/.env
      - ../.database:/.database
      - ../.static:/.static
      - ../.media:/.media
    command: bash -c "cd src &&
                      python manage.py migrate &&
                      python manage.py collectstatic --noinput &&
                      python manage.py runserver 0.0.0.0:8000"
    restart: always
networks:
  default:
    external: true
    name: tkp-quiz_network
